### PR TITLE
Few More Options Added

### PR DESCRIPTION
**Pull request by technofreaky**
1. Set Message As Sticky Utill User Clicke delete
2. Set If MSG Wraper Need

# How To Create Sticky
Enter *0* as value for `$times`

# With Or With Out Default Wrapper
`WP_Error_Notice($content, $times = 1, Array $screen = array(), Array $users = array(), $WithWraper = true)`
Without Wrapper
Enter *true / false* if default wrapper

### CODE REVIEW

**Comment by technofreaky** [comment]
Use {msgID} to get the id of the message in message string

**Comment by panvagenas** [comment]
Hey technofreaky,

Thank you for your contribution. 

I'm ok with (1) but can't see (2) implemented. I see you added the property `WP_Notice::$WithWraper` but except from the constructor and the getter or setter I can't see any use for it. Maybe you would like to use it in `WP_Notice::getContentFormated()` method but you should leave `$wrapInParTag = true` param to the same method for backward compatibility. 

Also it'll be nice if you add the new options in readme.

Thanks again!

**Comment by technofreaky** [comment]
@panvagenas sure let me add. i customized few thing for my plugin let me try to add those options too.

**Comment by panvagenas** [comment]
@technofreaky great! Please make a new pull request with the new options fully implemented!

**Comment by technofreaky** [comment]
@panvagenas i need one help you please contact me via https://technofreaky.campfirenow.com/89dd8

**Comment by technofreaky** [comment]
@panvagenas kindly use this link please
https://technofreaky.campfirenow.com/58ebe
its a guest chat

**Comment by technofreaky** [comment]
@panvagenas i tried to add more features but. your repo was updated. 

can you please merge it from My repo ?
https://github.com/technofreaky/wp-admin-notices/blob/master/WP_Admin_Notices.php

**Comment by panvagenas** [comment]
@technofreaky I released a new version in which I also implemented you sticky option. This is actually a major release and changed the script a lot. You can still use the v1.0.0 but please take a look at the new version also.

Thank you for your help!

**Comment by technofreaky** [comment]
@panvagenas hi, i just need a small help. can you please tell me when you are free
My id : varunsridharan23@gmail.com

**Pull request closed without merging**
